{% autoescape false %}

{{ conf | except("proxy-groups") | yaml }}

proxy-groups:
- name: '♻️ Automatic'
  type: 'url-test'
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}
{{ conf.get("proxy-groups", []) | yaml }}

{% endautoescape %}